name: LVNLUX
favicon: null
layout_spectrum: 0.7440568557940423
typography_spectrum: 0.19398942193947732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8950997109059244
  lightness: 0.14009804045781493
  saturation: 0.13136844616383314
  rhythmicContrast: 0.43361013219691813
purpose: []
